kamranahmedse/git-standup

README.md
git-standup

The example documentation had the week start and end info at the end of the command, not first.

Add support for a folder of repos & fix some typos.

---

git-standup

This change corrects the case of SINCE making the command valid, as "$since" is not defined but "$SINCE" is.

Correct case of SINCE variable

---

installer.sh

Improve the installation speed by fetching only latest snapshot of the source file. This will be particularly useful in slow networks.

Installer: Take only recent snapshot in git clone

---

Makefile

The Makefile currently supports `prefix`, but it will balk if the directories under `prefix` do not already exist.
```
$ make install prefix=/tmp/test-prefix
install -m 0755 git-standup /tmp/test-prefix/bin
install: /tmp/test-prefix/bin: No such file or directory
make: *** [install] Error 71
```
This adds a directory creation step. It also sets up some more directory variables based on [GNU's Makefile conventions](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables) in the expectation of later supporting a `man` page and other stuff in conjunction with `prefix` and package managers, like requested in #9.

Makefile: fix 'make install' for alternate prefixes

---

README.md
package.json

Anyone can install easily with npm like below with this patch.
```
$ npm install -g git-standup
```
I added it on npmjs.com for testing https://www.npmjs.com/package/git-standup
Of course, if you want, I'll remove the npm package and then you can add it on npmjs. :-)
And we can use this more useful with below packages;
- https://www.npmjs.com/package/mgit
- https://www.npmjs.com/package/clone-org-repos

Make as a node package to make easy to install

---

git-standup

Fixes some errors that happen when you run `git standup` when it's not connected to a terminal, or that TTY does not support colors.
Needed for full support of #9, since package manager build & tests may be run in headless contexts.

Fix handling of no-tty or no-color-support cases

---

git-standup

Adds an explicit -h "help" option so you can ask for help in ways besides putting in invalid options. 
This allows you to do 'git standup -h' and have it exit success. Useful for a smoke test in things like Mac Homebrew.
Modifies `getopts` usage to avoid syntax errors when invalid options are passed.
The help screen is longer now, so it's only displayed when you do `git standup -h`. Usage errors are kept short, to keep focus on the particular error that `getopts` found.
Now, when you have a bad option supplied, it'll do this:
```
$ git standup -x
/Users/janke/local/opp/git-standup/git-standup: illegal option -- x
Use 'git standup -h' to see usage info
```

Add explicit -h "help" option and longer usage message

---

git-standup

I just started using `git-standup` and found it generated a warning when `find` was called. This PR fixes that warning.

Fix find warning

---

git-standup

Allowed values for `-D` are the same as the allowed values for the `--date` flag for `git log`. The default is `relative` to maintain the existing behavior.

Allow date format to be specified with -D

---

README.md
git-standup

This feature adds a CLI option -L that toggles whether symbolic links should be followed when in the recursive directory search.
I have multiple cloned repositories in different places in my filesystem hierarchy. For ease of access and delimiting of search among other reasons, I keep a `_current_projects` folder containing symbolic links to repositories I am actively working on. This patch allows me to execute `git standup` in my `_current_projects` directory.

Add possibilities to follow symlinks when performing recursive directory search

---

README.md
git-standup

This change is especially useful if you have many projects on the go with multiple contributors.
I'm not sure how verbose you would like the output to be, so I just have a single `echo` statement telling the user that we are running `git fetch`. However it may be useful to give the user feedback on progress if they are fetching multiple repositories.
Similarly, I didn't know if you want to stop execution, print the error and continue on or whatever if `git fetch` fails, so I left it redirecting to `/dev/null`.

Add option to run `git fetch --all` before standup

---

git-standup

Git submodules use a file instead of a folder for their .git and inside that file is a reference to the actual location of the .git folder. git-standup should check for a file too and then git will handle git log in the exact same way. Fixes #56

Add support for git submodules

---

git-standup

Seems like in my versions of git/bash, git thinks the tty used in that
eval call does not support colored output and fallbacks to non-colored.
This overrides that by specifiying the color parameter.

Ensure color usage

---

git-standup

Very basic flag that enables option for `-u`, specifying `--until="## days ago"`.
https://github.com/kamranahmedse/git-standup/issues/54

Add option for -u, until days ago

---

Makefile

This allows to do something like `PREFIX=~/.local make install`, so `git-standup` ends where I need to without modifying base system.

Allow redefining PREFIX and other vars

---

README.md
git-standup

I usually have a directory containing all kinds of git repos so whitelisting repos helps a lot.

Add support for whitelisting search paths

---

git-standup

I would like to see branch names and tags for each commit in the output.
Adding `%d` to `git log`'s `--pretty=format:` parameter gives us tags and branch names printed. 
Unfortunately, this is not a perfect solution, as it won't display branch name unless the commit is the last one on the branch. Not sure how could it be solved, or even if it's possible without massive changes in the project.
Any hints on how to improve this will be appreciated.

Show branch names and tags

---

git-standup

Closes #54 
Also kinda improves on #91
Not sure about the flag names but these make sense to me `-A` commits for after and `-B` for before.
For example to list commits from last Monday this can be used
git standup -A "2018-10-01 00:00" -B "2018-10-01 23:59" -D iso

Add before and after options

---

git-standup

@kamranahmedse , Add a optional '-c' to see diffstat of every commit like below.
[root@centos7 git-standup]# **git-standup -a all -c**
> a75f895 - Remove test echo (3 minutes ago) < Zongpeng Qiao >
**git-standup | 1 -
1 file changed, 1 deletion(-)**
> b62d81e - add support for diffstat of every commit with extra option -c (7 minutes ago) < Zongpeng Qiao >
**git-standup | 14 ++++++++++----
1 file changed, 10 insertions(+), 4 deletions(-)**

Add support for diffstat of every commit with extra option -c

---

README.md
git-standup

Solves #92
This sets the author date in GIT_PRETTY_FORMAT if -R option is used
Commit dates change when there are rebases or merges and you want to know when the commit was originally made and not when it was added to a branch or rebased on.
Now we can with the `-R` option
```sh
$ git-standup -D local -R
e75ed6a - Commit Message (Thu Nov 22 11:18:27 2018) <Andre Marcelo-Tanner>
```
```sh
$ git-standup -D local
e75ed6a - Commit Message (Thu Nov 22 13:19:00 2018) <Andre Marcelo-Tanner>
```

Option to show Author Date instead of Committer Date

---

git-standup

Defer grabbing git user until `cd`ing into each git dir. This means that local git users are respected and ensures accurate reporting
Fixes #98

respect local git user

---

snap/snapcraft.yaml

git-standup is awesome, thanks for making it. We recently had a team sprint and it was great to be able to summarise all the work done with one command. Love it <3 
During that sprint I created a snap package of git-standup so it can be featured in the [Snap Store](https://snapcraft.io/store), which is a cross-distribution app-store for Linux. Once in the store, it can be easily installed via ‘snap install’ or via GNOME Software or KDE Discover on most distros.
A single snap (built for many architectures) in the Snap Store will be installable on numerous popular Linux distributions with no changes. It’ll also be discoverable via the [Snap Store](https://snapcraft.io/store), where releases are under your control.
If you're willing to publish this under the git-standup project name, you …

Add snapcraft support to build snaps

---

git-standup

I personally had no idea it uses the same format as git log, my first try was to write `git standup -D absolute` (cause you know, absolute is the opposite of relative xd), that made me look into the source code.

made -D option more descriptive

---

git-standup

This PR softens the language used when no commits are found. 
I just installed git-standup, and it's awesome! I have a lot of projects that I work on, but I tend to focus on just a few. When I ran `git standup` today, I saw my commits from yesterday, but I also saw this for the projects I didn't touch:
It didn't make me feel great about myself. I suspect that using this everyday and seeing a bunch of messages saying "Seems like Steven Hicks did nothing!" would wear on me. A message like "No commits from Steven Hicks during this period" carries less judgement.
I know, I know...this is the most snowflake of PR's ever, but 🤷‍♂️. Language matters.

Use more friendly language when no commits found

---

git-standup

Introduces the `-b foobar` option, which restricts returned results to
commits present on branch "foobar". Supports arbitrary branch specs, so
for example `-b origin/foobar` would include data present on the remote
that has not been merged locally.
Fixes #109

feat(filter): add option to specify branch filter

---

git-standup

Let the user know there is an "all" filter for the -a option.

Updated usage function to clarify the -a option.

---

README.md
git-standup

Fix a tiny typo in the description of the `-F` option.

Fix a typo
